nowe_porzadki/blog_2/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .feeds import LatestPostFeed
app_name='blog_2'
urlpatterns = [
    path('', views.Post_list, name='Post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.Post_list, name='post_list_by_tag'),
    path('feed/',LatestPostFeed(), name='post_feed'),
    path('new_post/', views.new_post, name='new_post'),



]

nowe_porzadki/nowe_porzadki/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_2.urls')),
    path('account/',include('account.urls')),



]

nowe_porzadki/blog_2/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

    #'wlasny menager filtruje tylko opublikowane
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (('draft','Draft'),('published','Published'),)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    tags = TaggableManager()  # dodaje meneger tagow
    'managery'
    objects = models.Manager()  # manager domyślny.
    published = PublishedManager()  # Własny menedżer.


    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title

    'tworzy sciezke  ze zmiennymi konkretnego posta z get absolute do samego siebie czyli do post'
    def get_absolute_url(self):
        return reverse('blog_2:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

class Comment(models.Model):
    # ponizej klucz obcy relacyjne pole Post.comments
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentarz dodany przez {} dla posta {}'.format(self.name, self.post)

nowe_porzadki/blog_2/forms.py
from django import forms
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {'body':''}

class new_postForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body','tags','status')
        widgets = {'body': forms.Textarea(attrs={'cols':130,'rows':10, })

                   }

class search_form(forms.Form):
    keyword = forms.CharField(label='', max_length=100)
    keyword.widget.attrs.update({'class': 'searchtextrea','placeholder':'Szukaj'})

nowe_porzadki/blog_2/views.py
from django.shortcuts import render
from taggit.models import Tag
# Create your views here.
from django.db.models import Count
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from .forms import CommentForm, new_postForm, search_form


def home(request):
    return render(request, 'blog_2/base.html')

def Post_list(request,tag_slug=None): #domyslnie nie ma taga

        object_list = Post.published.all()
        tag = None
        keyword2="poczatkowe"
        result=None
        searched = False
        if request.method == 'POST':
            s_form = search_form(data=request.POST)

            if s_form.is_valid():
                searched = True
                keyword2 = s_form.cleaned_data['keyword']

                object_list= Post.published.filter(title__icontains=keyword2)

                if not  object_list:
                    object_list = Post.published.filter(body__icontains=keyword2)
                if  object_list:
                    result = True

        else:
            s_form = search_form()

        if tag_slug:

            tag = get_object_or_404(Tag,slug=tag_slug)
            object_list = object_list.filter(tags__in=[tag])



        paginator = Paginator(object_list, 3)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts= paginator.page(paginator.num_pages)

        return render(request, 'blog_2/post_list.html', {'page': page, 'posts': posts, 'tag':tag,'s_form':s_form,'result':result, 'searched':searched })

def post_detail(request, year,month, day,post):
    post = get_object_or_404(Post, slug=post,status='published',publish__year = year,publish__month = month,publish__day = day)


    comments = post.comments.filter(active=True) # dzieki related name mozna uzyc post.comments

    if request.method == 'POST':
        # Komentarz został opublikowany.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Utworzenie obiektu Comment, ale jeszcze nie zapisujemy go w bazie danych.
            new_comment = comment_form.save(commit=False)
            new_comment.name = request.user

            # Przypisanie komentarza do bieżącego posta.
            new_comment.post = post
            # Zapisanie komentarza w bazie danych.
            new_comment.save()
    else:
        comment_form = CommentForm()
        #agregate do obliczen np avg srednia
        # annotate do ulozenia wynikow np po liczbie wspolnych tagow
    post_tags_ids = post.tags.values_list('id',flat=True) # zracane sa krotki z wattosciami z danych pol
    similar_posts = Post.published.filter(tags__in = post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags= Count('tags')).order_by('same_tags','-publish')[:3]
    return render(request, 'blog_2/post_detail.html', {'post': post,'comments':comments,'comment_form':comment_form,'similar_posts':similar_posts})

@login_required()
def new_post(request):

    if request.method == 'POST':

        new_post = new_postForm(data=request.POST)

        if new_post.is_valid():

            #wazne dopisanie czegos z autoamtu do form
            post = new_post.save(commit=False)

            post.author = request.user
            post.slug = post.title[:3]
            post.save()
            # zapis many to many aby tagi sie zpisaly z form
            new_post.save_m2m()
            messages.success(request, 'Pomyslnie dodano nowy Post')
        else:
            messages.warning(request,'uzupelnij poprawnie wszystkie pola')
    new_post = new_postForm()
    return render(request, 'blog_2/new_post.html',{'new_post':new_post,})

nowe_porzadki/blog_2/templates/blog_2/base.html
{% load static %}

<!-- Navigation -->
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'blog_2.css' %}">
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
  <div class="container">
    <a class="navbar-brand" href="#">Witaj! {{user.username}} </a>
    {% if user.is_authenticated %}
    <a href ="{% url 'logout' %}">wyloguj</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">

      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">glówna
                <span class="sr-only">(current)</span>
              </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog_2:new_post' %}">add new post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">dwa</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Page Content -->
<div class="container">
  <div class="card border-0 shadow my-5">
    <div class="card-body p-5">

      <h1 class="font-weight-light">

        <div class="title">
        {% block tit %}
        {% endblock %}
          </div>
      </h1>

      <div class="onepost1">

      {% block content %}
        {% endblock %}
      </div>

      <div style="height: 700px"></div>

    </div>
  </div>

</div>

</html>

nowe_porzadki/blog_2/templates/blog_2/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{post.get_absolute_url }}">{{post.title}}</a>
    </li>
    {% endfor %}
</ul>

nowe_porzadki/blog_2/templates/blog_2/new_post.html
{% extends 'blog_2/base.html' %}

{% block content %}

{% if messages %}
<div class="successMessage">
    <div class="messagebody">
<ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags}}">
        {{ message|safe }}
        <a href="{% url 'blog_2:Post_list' %}" class="close">x</a>
    </li>
    {% endfor %}
</ul>
        </div>
</div>
<br>
{% endif %}

<form action="." method="post">
    {{new_post.as_p}}
    {% csrf_token %}
    <p>

        <input type="hidden"  >
   <button  class="btn btn-primary" type="submit"> Dodaj nowy Post </button>
    </p>
</form>
{% endblock %}

nowe_porzadki/blog_2/templates/blog_2/pagination.html
{% block pagination %}
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
    {% endif %}
    <span class="current">
      Strona {{ page.number }} z {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Następna</a>
      {% endif %}
  </span>
</div>
{% endblock%}

nowe_porzadki/blog_2/templates/blog_2/post_detail.html
{% extends 'blog_2/base.html' %}

{% block tit %}
{{ post.title }}
{% endblock %}

{% block content %}
{% load static %}
<div class="obrazekPostDetail">
     {% with 'images/'|add:post.title|add:'.jpg' as image_static %}
     <img src="{% static image_static %}"width="100%" height="100%"/>
    {% endwith %}
</div>
<br>
<p class="'date">
    opublikowany {{post.publish}} przez {{post.author}}
</p>
{{post.body|linebreaks}}
{% with comments.count as total_comments %}
<h5>
    {{total_comments}} komentarz{{total_comments|pluralize:"y"}}
</h5>
{% endwith %}
Podobne posty :
{% for post in similar_posts %}
    <a href= "{{ post.get_absolute_url }}" >
    {{post.title}}
</a>
{% empty %}
Nie ma podobnych postow
{% endfor %}
<br>
{% for comment in comments %}
<div class="comment">
    <div class="com_detail">
   <b>&nbsp komentarz {{forloop.counter}} dodany przez {{comment.name }}
       {{comment.created}}</b>
    </div>
    <div class="body_com">
   {{comment.body|linebreaks }}
    </div>
</div>
{% empty %}
nie ma jeszcze komentarzy
{% endfor %}

{% if new_comment %}
twoj komentarz zostal dodany
{% else %}


<h3>
dodaj nowy komentarz
</h3>
<form action="." method="post">
    {{comment_form.as_p}}
    {% csrf_token %}

    {% if user.is_authenticated %}
    <p><input type="submit" value="dodaj komentarz"></p>
    {% else %}
    <a href="{% url 'login' %}">zaloguj</a>
     sie aby dodać komentarz
    {% endif %}
</form>
{% endif %}

{% endblock %}

nowe_porzadki/blog_2/templates/blog_2/post_list.html
{% extends 'blog_2/base.html' %}

{% block tit %}
<div class="pptitle">

<div class="titleBLOG">
    {% load blog_2_tags %}
    {% load static %}

<img src="{% static 'images/logo_blog.png' %}"/>

</div>
    <div class="Bdetails">
         opublikowano {% total_posts %} postów
        najnowsze posty:
<br>
{% show_latest_posts 3 %}
najczesciej komentowane :
{% get_most_commented_posts as most_commented_posts %}
<ul>

    {% for post in most_commented_posts %}
    <li>
        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    </li>
    {% endfor %}
</ul>
         <div class ="rss">

            <a href= "{% url 'blog_2:post_feed' %}" class="top-menu">  subskrybuj kanal RSS  <span class="glyphicon glyphicon-star">  </span></a>

        </div>
         </div>
    </div>
<div class="searcher">
    <form action="." method="post" >
        <div class="lupka">
     <span  class="glyphicon glyphicon-search">  </span>
</div>
    {% csrf_token %}
    {{ s_form.as_p }}


    <button type="submit" class="btn btn-primary">szukaj</button>

    </form>

</div>

{% endblock %}






{% block content %}
{% if tag %}
Posty oznaczone tagiem "{{tag.name}}"

{% endif %}

{% if searched %}
{% if result %}
znaleziono:
{% else %}
niestety wyszukiwanie nie przynioslo zadnych wynikow, polecane posty
{% get_most_commented_posts as most_commented_posts %}
{% for post in most_commented_posts %}
    <li>
        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    </li>
    {% endfor %}

{% endif %}

{% endif %}

{% if posts %}
    {% for post in posts %}




<div class="onepost">
<div class="obrazekpost">
    {% with 'images/'|add:post.title|add:'.jpg' as image_static %}
     <img src="{% static image_static %}"width="100%" height="100%"/>
 {% endwith %}

</div>

<h3>
    <a href= "{{ post.get_absolute_url }}" >
    {{ post.title }}
    </a>
    </h3>
<h4 class="postbody" >
    {{ post.body|truncatewords:30|linebreaks }}
    <p class="tags">
        Tags:
        {% for tag in post.tags.all %}

        <a href ="{% url 'blog_2:post_list_by_tag' tag.slug %}">

        {{ tag.name}}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </a>

    </p>

    </h4>



    </div>


    {% endfor %}
{% endif %}
{% include "blog_2/pagination.html" with page=posts %}
{% endblock %}